"""Generate CLI documentation from Click commands.

This script automatically generates markdown documentation from the NHL Scrabble
Click CLI interface. The generated documentation is always up-to-date with the
actual CLI implementation.

Usage:
    python scripts/generate_cli_docs.py

Output:
    docs/reference/cli-generated.md
"""

# ruff: noqa: INP001, S603, S607, T201
# INP001: scripts directory is not a package
# S603/S607: subprocess calls to nhl-scrabble CLI (trusted input)
# T201: print statements are appropriate for utility script

from __future__ import annotations

import subprocess
import sys
from pathlib import Path


def run_cli_command(*args: str) -> str:
    """Run a CLI command and capture its output.

    Args:
        *args: Command arguments to pass to nhl-scrabble

    Returns:
        Command output as string

    Raises:
        subprocess.CalledProcessError: If command fails
    """
    result = subprocess.run(
        ["nhl-scrabble", *args],
        capture_output=True,
        text=True,
        check=True,
    )
    return result.stdout


def generate_cli_docs() -> None:
    """Generate markdown CLI documentation from Click commands."""
    output_file = Path("docs/reference/cli-generated.md")

    # Ensure output directory exists
    output_file.parent.mkdir(parents=True, exist_ok=True)

    # Get main CLI help
    try:
        main_help = run_cli_command("--help")
    except subprocess.CalledProcessError as e:
        print(f"Error: Failed to get main CLI help: {e}", file=sys.stderr)
        sys.exit(1)

    # Get analyze command help
    try:
        analyze_help = run_cli_command("analyze", "--help")
    except subprocess.CalledProcessError as e:
        print(f"Error: Failed to get analyze command help: {e}", file=sys.stderr)
        sys.exit(1)

    # Build documentation content
    content = f"""# CLI Reference (Auto-Generated)

> **⚠️ Auto-Generated Documentation**
>
> This file is automatically generated from the Click CLI using `scripts/generate_cli_docs.py`.
> **DO NOT EDIT MANUALLY** - Changes will be overwritten.
>
> To update: `make docs-cli` or `python scripts/generate_cli_docs.py`

______________________________________________________________________

## Overview

The NHL Scrabble command-line interface provides commands for analyzing NHL roster
data and calculating Scrabble scores for player names.

For usage tutorials, see [Getting Started](../tutorials/01-getting-started.md).

For configuration details, see [Configuration Reference](configuration.md) and
[Environment Variables](environment-variables.md).

______________________________________________________________________

## Main Command

```
{main_help}```

______________________________________________________________________

## `analyze` Command

The `analyze` command fetches current NHL roster data and generates comprehensive
reports with Scrabble scores.

```
{analyze_help}```

### Examples

**Basic usage (text output to stdout):**

```bash
nhl-scrabble analyze
```

**JSON output to file:**

```bash
nhl-scrabble analyze --format json --output report.json
```

**Verbose logging:**

```bash
nhl-scrabble analyze --verbose
```

**Custom top players count:**

```bash
nhl-scrabble analyze --top-players 50 --top-team-players 10
```

**Disable caching:**

```bash
nhl-scrabble analyze --no-cache
```

**Clear cache before running:**

```bash
nhl-scrabble analyze --clear-cache
```

______________________________________________________________________

## Configuration

The CLI can be configured via:

1. **Command-line options** (highest priority)
1. **Environment variables** (medium priority)
1. **`.env` file** (lowest priority)

See [Environment Variables](environment-variables.md) for available configuration options.

______________________________________________________________________

## Exit Codes

| Code | Meaning |
|------|---------|
| 0    | Success |
| 1    | General error (API error, file I/O error, etc.) |

______________________________________________________________________

## Related Documentation

- [Getting Started Tutorial](../tutorials/01-getting-started.md) - First steps with NHL Scrabble
- [Understanding Output](../tutorials/02-understanding-output.md) - How to read the reports
- [Configuration Reference](configuration.md) - All configuration options
- [Environment Variables](environment-variables.md) - Environment variable reference
- [API Reference](api/index.html) - Python API documentation

______________________________________________________________________

*Generated by `scripts/generate_cli_docs.py` - Do not edit manually*
"""

    # Write to file
    output_file.write_text(content)
    print(f"✓ Generated {output_file}")


if __name__ == "__main__":
    generate_cli_docs()
